import '@/app/diseño/global.css';
import { Metadata } from 'next';
import { inter } from './diseño/fonts';
 
export const metadata: Metadata = {
  title: "ShopSelect",
  description: "Generated by create next app"
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased bg-cyan-800 ` }>
        
        {children}</body>
    </html>
  );
}
